import { StyleSheet } from 'react-native';

import { Colors } from '@/constants/Colors';
import { fonts } from '@/constants/fonts';
import { spacing } from '@/constants/spacing';
import { typography } from '@/constants/typography';
import { AUTH_CONTENT_MAX_WIDTH } from '@/styles/auth/screen';

export const authFormStyles = StyleSheet.create({
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: Colors.auth.googleBorder,
    backgroundColor: Colors.white,
    paddingVertical: 12,
    paddingHorizontal: 24,
    gap: 16,
  },
  googleIcon: {
    width: 24,
    height: 24,
  },
  googleLabel: {
    fontFamily: fonts.onest,
    fontSize: 16,
    fontWeight:'500',
    color: '#121926'
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginVertical: spacing.sm,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: Colors.auth.inputBorder,
  },
  dividerText: {
    fontFamily: fonts.onest,
    fontSize: 16,
    fontWeight: '400',
    color: '#121926',
  },
  field: {
    gap: 8,
  },
  fieldLabel: {
    fontFamily: fonts.onestBold,
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 25,
    color: '#010511',
  },
  fieldInputWrap: {
    position: 'relative',
    minHeight: 50,
    borderWidth: 1,
    borderColor: Colors.auth.inputBorder,
    borderRadius: 12,
    backgroundColor: Colors.white,
    justifyContent: 'center',
  },
  fieldPlaceholder: {
    ...typography.authInputPlaceholder,
    fontFamily: fonts.cabin,
    color: Colors.auth.inputPlaceholder,
    position: 'absolute',
    left: 16,
    right: 16,
    top: 14,
  },
  fieldInput: {
    minHeight: 50,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontFamily: fonts.onest,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    color: Colors.auth.title,
    backgroundColor: 'transparent',
  },
  passwordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.auth.inputBorder,
    borderRadius: 12,
    backgroundColor: Colors.white,
    minHeight: 50,
    paddingRight: 12,
    position: 'relative',
  },
  passwordPlaceholder: {
    ...typography.authInputPlaceholder,
    fontFamily: fonts.cabin,
    color: Colors.auth.inputPlaceholder,
    position: 'absolute',
    left: 16,
    right: 48,
    top: 14,
  },
  passwordInput: {
    flex: 1,
    minHeight: 50,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontFamily: fonts.onest,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    color: Colors.auth.title,
    backgroundColor: 'transparent',
  },
  hintBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: Colors.auth.hintBg,
  },
  hintText: {
    flex: 1,
    fontFamily: fonts.onest,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 22,
    color: '#364152',
  },
  forgotRow: {
    alignItems: 'flex-end',
    marginTop: -4,
  },
  forgotLink: {
    fontFamily: fonts.onest,
    fontSize: 16,
    fontWeight: '400',
    color: '#4062B9',
  },
  termsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginTop: spacing.sm,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: Colors.auth.inputBorder,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: Colors.auth.link,
    borderColor: Colors.auth.link,
  },
  termsText: {
    flex: 1,
    ...typography.authInputPlaceholder,
    fontFamily: fonts.cabin,
    color: Colors.auth.inputPlaceholder,
  },
  termsLink: {
    ...typography.authInputPlaceholder,
    fontFamily: fonts.onest,
    color: Colors.auth.googleLabel,
  },
  biometricCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: AUTH_CONTENT_MAX_WIDTH,
    height: 85,
    borderRadius: 15,
    backgroundColor: Colors.auth.biometricBg,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 12,
    paddingRight: 12,
  },
  biometricLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
    marginRight: 8,
  },
  biometricIcon: {
    width: 32,
    height: 32,
  },
  biometricToggleTrack: {
    width: 49,
    height: 25,
    borderRadius: 50,
    backgroundColor: Colors.auth.biometricToggleTrack,
    padding: 2,
    justifyContent: 'center',
  },
  biometricToggleThumb: {
    width: 21,
    height: 21,
    borderRadius: 21,
    backgroundColor: Colors.auth.biometricToggleThumb,
  },
  biometricToggleThumbOn: {
    alignSelf: 'flex-end',
  },
  biometricCopy: {
    flex: 1,
    gap: 2,
  },
  biometricTitle: {
    fontFamily: fonts.onestBold,
    fontSize: 14,
    fontWeight: '700',
    color: Colors.auth.biometricTitle,
  },
  biometricSubtitle: {
    fontFamily: fonts.onest,
    fontSize: 12,
    fontWeight: '400',
    color: Colors.auth.biometricSubtitle,
  },
});
