import { Platform, StyleSheet } from 'react-native';

import { fonts } from '@/constants/fonts';
import { homeColors, homeLayout } from '@/constants/home';

export const homeHeaderStyles = StyleSheet.create({
  headerShell: {
    width: '100%',
    overflow: 'hidden',
    borderBottomLeftRadius: homeLayout.headerBottomRadius,
    borderBottomRightRadius: homeLayout.headerBottomRadius,
    backgroundColor: homeColors.headerGradientEnd,
    ...Platform.select({
      ios: { borderCurve: 'continuous' },
      default: {},
    }),
  },
  gradient: {
    width: '100%',
    paddingHorizontal: homeLayout.screenPaddingHorizontal,
    paddingBottom: homeLayout.headerPaddingBottom,
  },
  gradientWithDecor: {
    position: 'relative',
    overflow: 'hidden',
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 16,
    zIndex: 1,
  },
  profileRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: homeLayout.headerAvatarGap,
    paddingRight: 12,
  },
  avatar: {
    width: homeLayout.headerAvatarSize,
    height: homeLayout.headerAvatarSize,
    borderRadius: homeLayout.headerAvatarSize / 2,
    backgroundColor: homeColors.headerAvatarBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitial: {
    fontFamily: fonts.cabinBold,
    fontSize: 14,
    lineHeight: 14,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  greetingBlock: {
    flex: 1,
    gap: 2,
  },
  greetingTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#FFFFFF',
    textTransform: 'capitalize',
  },
  greetingSubtitle: {
    fontFamily: fonts.cabin,
    fontSize: 13,
    lineHeight: 20.8,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.85)',
  },
  notificationButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationIcon: {
    width: 24,
    height: 24,
    objectFit: 'contain',
    resizeMode: 'contain',
  },
  spendingBlock: {
    marginBottom: 14,
    zIndex: 1,
  },
  spendingContent: {
    gap: 4,
    paddingRight: 72,
  },
  averageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  averageLabel: {
    fontFamily: fonts.cabin,
    fontSize: 13,
    lineHeight: 20.8,
    color: 'rgba(255,255,255,0.9)',
  },
  amount: {
    fontFamily: fonts.cabinBold,
    fontSize: 40,
    lineHeight: 48,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  currency: {
    fontSize: 32,
  },
  budgetHint: {
    fontFamily: fonts.cabin,
    fontSize: 13,
    lineHeight: 20.8,
    color: 'rgba(255,255,255,0.75)',
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: homeLayout.headerButtonGap,
    zIndex: 1,
  },
  createBudgetButton: {
    flex: 1,
    maxWidth: homeLayout.headerButtonWidth,
    height: homeLayout.headerButtonHeight,
    borderRadius: 50,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  plusCircleDark: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: '#121926',
    alignItems: 'center',
    justifyContent: 'center',
  },
  createBudgetLabel: {
    fontFamily: fonts.cabinBold,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '700',
    color: '#121926',
  },
  expenseHistoryButton: {
    flex: 1,
    maxWidth: homeLayout.headerButtonWidth,
    height: homeLayout.headerButtonHeight,
    borderRadius: 50,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: homeColors.headerBlue,
    borderWidth: 1,
    borderColor: homeColors.expenseHistoryBorder,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  expenseHistoryIcon: {
    width: 18,
    height: 18,
  },
  expenseHistoryLabel: {
    fontFamily: fonts.cabinBold,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  pressed: {
    opacity: 0.88,
  },
});
