import { StyleSheet } from 'react-native';

import { Colors } from '@/constants/Colors';
import { fonts } from '@/constants/fonts';

export const onboardingScreenStyles = StyleSheet.create({
  twoColGrid: {
    width: '100%',
    alignSelf: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    columnGap: 16,
    rowGap: 16,
  },
  step1Grid: {
    marginBottom: 18,
  },
  step2Grid: {
    columnGap: 8,
    rowGap: 8,
    marginBottom: 12,
  },
  issueCard: {
    width: '47.6%',
    maxWidth: 183,
    height: 149,
    borderWidth: 1,
    borderRadius: 13,
    borderColor: '#E3E8EF',
    backgroundColor: Colors.white,
    paddingTop: 16,
    paddingHorizontal: 14,
    paddingBottom: 16,
  },
  issueIconBadge: {
    width: 36,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#F2F2F2',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    paddingTop: 5,
    paddingRight: 7,
    paddingBottom: 3,
    paddingLeft: 8,
  },
  issueIconImage: {
    width: 24,
    height: 24,
  },
  issueTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#20315C',
    marginBottom: 4,
  },
  issueDesc: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '400',
    color: '#697586',
  },
  categoryCard: {
    width: '47.6%',
    maxWidth: 183,
    height: 143,
    borderWidth: 1,
    borderRadius: 13,
    borderColor: '#E3E8EF',
    backgroundColor: Colors.white,
    paddingTop: 12,
    paddingHorizontal: 12,
    paddingBottom: 10,
  },
  categoryIconImage: {
    width: 24,
    height: 24,
  },
  categoryTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    color: '#20315C',
    marginBottom: 4,
  },
  categoryDesc: {
    fontFamily: fonts.cabin,
    fontSize: 11,
    lineHeight: 17,
    fontWeight: '400',
    color: '#697586',
  },
  incomeGrid: {
    width: '100%',
    alignSelf: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    columnGap: 16,
    rowGap: 16,
  },
  step3Body: {
    gap: 16,
    marginBottom: 12,
  },
  incomeCard: {
    width: '47.6%',
    maxWidth: 183,
    minHeight: 67,
    borderWidth: 1,
    borderRadius: 13,
    borderColor: '#E3E8EF',
    backgroundColor: Colors.white,
    paddingTop: 10,
    paddingHorizontal: 12,
    paddingBottom: 10,
  },
  incomeTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#20315C',
  },
  incomeSub: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '400',
    color: '#697586',
    marginTop: 2,
  },
  infoBanner: {
    width: 382,
    height: 76,
    borderWidth: 1,
    borderColor: '#E3E8EF',
    borderRadius: 8,
    backgroundColor: '#F2F2F2',
    padding: 12,
    flexDirection: 'row',
    gap: 16,
    alignItems: 'flex-start',
  },
  infoText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 22,
    color: '#697586',
  },
  thresholdList: {
    width: '100%',
    maxWidth: 382,
    alignSelf: 'center',
    gap: 16,
  },
  thresholdCard: {
    width: '100%',
    maxWidth: 382,
    height: 196,
    borderWidth: 1,
    borderColor: '#E3E8EF',
    borderRadius: 13,
    padding: 16,
    backgroundColor: '#F2F2F2',
    gap: 16,
  },
  thresholdHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  thresholdHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  thresholdIconBox: {
    width: 38,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 5,
    paddingRight: 7,
    paddingBottom: 5,
    paddingLeft: 7,
  },
  thresholdIconImage: {
    width: 24,
    height: 24,
  },
  thresholdTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#20315C',
  },
  thresholdDesc: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '400',
    color: '#697586',
  },
  badge: {
    height: 30,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    paddingTop: 7,
    paddingRight: 12,
    paddingBottom: 7,
    paddingLeft: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeRelaxed: {
    width: 65,
    backgroundColor: '#E4E8F2',
  },
  badgeRecommended: {
    width: 103,
    backgroundColor: '#FAF0E2',
  },
  badgeBrave: {
    width: 53,
    backgroundColor: '#FBD9D7',
  },
  badgeText: {
    fontFamily: fonts.cabin,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
  },
  badgeTextRelaxed: {
    color: '#4062B9',
  },
  badgeTextRecommended: {
    color: '#C68000',
  },
  badgeTextBrave: {
    color: '#D14343',
  },
  progressTrack: {
    width: 296,
    height: 10,
    borderRadius: 50,
    backgroundColor: '#DDDDDD',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 50,
    backgroundColor: '#4062B9',
  },
  progressFill50: {
    width: '50%',
  },
  progressFill70: {
    width: '70%',
    backgroundColor: '#BF955B',
  },
  progressFill90: {
    width: '90%',
    backgroundColor: '#C3382C',
  },
  progressLabelRow: {
    width: 296,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  progressLabel: {
    fontFamily: fonts.cabin,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
    color: '#15213E',
  },
  cardSelected: {
    backgroundColor: Colors.onboarding.cardSelectedBg,
    borderColor: Colors.onboarding.cardSelectedBorder,
    borderWidth: 1,
  },
  cardTitleSelected: {
    color: Colors.onboarding.cardSelectedText,
  },
  cardDescSelected: {
    color: Colors.onboarding.cardSelectedText,
  },
  iconBadgeSelected: {
    backgroundColor: Colors.onboarding.iconBadgeSelectedBg,
  },
  iconImageSelected: {
    tintColor: '#FFFFFF',
  },
});
