import { StyleSheet } from 'react-native';

import { accountSettingsColors, accountSettingsLayout } from '@/constants/settings';
import { fonts } from '@/constants/fonts';

export const accountSettingsStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: accountSettingsColors.pageBg,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: accountSettingsLayout.screenPaddingH,
    paddingBottom: 32,
    gap: 20,
  },
  profileSection: {
    alignItems: 'center',
    gap: 10,
    paddingTop: 8,
    paddingBottom: 4,
  },
  avatarWrap: {
    width: accountSettingsLayout.avatarSize,
    height: accountSettingsLayout.avatarSize,
  },
  avatar: {
    width: accountSettingsLayout.avatarSize,
    height: accountSettingsLayout.avatarSize,
    borderRadius: accountSettingsLayout.avatarSize / 2,
    backgroundColor: accountSettingsColors.avatarBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitials: {
    fontFamily: fonts.cabinBold,
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  avatarEditButton: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: accountSettingsLayout.avatarEditSize,
    height: accountSettingsLayout.avatarEditSize,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: accountSettingsColors.avatarEditBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileName: {
    fontFamily: fonts.cabinBold,
    fontSize: 18,
    lineHeight: 28.8,
    fontWeight: '700',
    color: accountSettingsColors.profileName,
    textAlign: 'center',
  },
  infoCard: {
    backgroundColor: accountSettingsColors.cardBg,
    borderRadius: accountSettingsLayout.cardRadius,
    borderWidth: 1,
    borderColor: accountSettingsColors.cardBorder,
    paddingVertical: accountSettingsLayout.cardPaddingV,
    paddingHorizontal: accountSettingsLayout.cardPaddingH,
    gap: accountSettingsLayout.cardGap,
  },
  infoCardTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 18,
    lineHeight: 28.8,
    fontWeight: '700',
    color: accountSettingsColors.sectionTitle,
  },
  infoRows: {
    gap: 0,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: accountSettingsLayout.rowMinHeight,
    paddingVertical: 12,
  },
  infoRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: accountSettingsLayout.dividerColor,
  },
  infoRowLabel: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: accountSettingsColors.label,
    flexShrink: 0,
  },
  infoRowRight: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    marginLeft: 12,
  },
  infoRowValue: {
    fontFamily: fonts.cabin,
    fontSize: 16,
    lineHeight: 25.6,
    color: accountSettingsColors.value,
    textAlign: 'right',
    flexShrink: 1,
  },
  infoRowAdd: {
    fontFamily: fonts.cabin,
    fontSize: 16,
    lineHeight: 25.6,
    color: accountSettingsColors.addLink,
    textAlign: 'right',
  },
  deleteCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: accountSettingsColors.deleteBg,
    borderRadius: accountSettingsLayout.deleteCardRadius,
    borderWidth: 1,
    borderColor: accountSettingsColors.deleteBorder,
    padding: accountSettingsLayout.deleteCardPadding,
    gap: 12,
  },
  deleteIconBox: {
    width: 40,
    height: 40,
  },
  deleteTextBlock: {
    flex: 1,
    gap: 2,
  },
  deleteTitle: {
    fontFamily: fonts.cabin,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '400',
    color: '#75211A',
  },
  deleteSubtitle: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    color: accountSettingsColors.deleteSubtitle,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    marginTop: 4,
  },
  logoutLabel: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: accountSettingsColors.logout,
  },
  pressed: {
    opacity: 0.85,
  },
});
