import { StyleSheet } from 'react-native';

import { expenseFlowColors, expenseFlowLayout } from '@/constants/expense-flow';
import { fonts } from '@/constants/fonts';

const {
  screenPaddingH,
  contextCardRadius,
  contextCardMinHeight,
  contextProgressWidth,
  contextProgressHeight,
  voiceCardRadius,
  voiceCardMinHeight,
  voiceMicCircleSize,
  voiceStartButtonHeight,
  voiceStartButtonGap,
  manualInputPadding,
  confirmCardRadius,
  inputRadius,
  inputHeight,
  contentGap,
  sectionGap,
  dividerLineColor,
} = expenseFlowLayout;

export const expenseFlowStyles = StyleSheet.create({
  content: {
    gap: sectionGap,
  },
  sectionHeading: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#121926',
  },
  promptText: {
    fontFamily: fonts.cabin,
    fontSize: 16,
    lineHeight: 25.6,
    color: '#121926',
  },
  contextCard: {
    minHeight: contextCardMinHeight,
    borderRadius: contextCardRadius,
    backgroundColor: expenseFlowColors.contextCardBg,
    borderWidth: 1,
    borderColor: expenseFlowColors.contextCardBorder,
    padding: 16,
    justifyContent: 'center',
  },
  contextTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
  },
  contextLeftCol: {
    flex: 1,
    gap: 2,
  },
  contextPrefix: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    color: '#121926',
  },
  contextBudgetName: {
    fontFamily: fonts.cabinBold,
    fontSize: 20,
    lineHeight: 32,
    fontWeight: '700',
    color: '#121926',
  },
  contextRemaining: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    color: '#121926',
    marginTop: 2,
  },
  contextRightCol: {
    alignItems: 'flex-end',
    gap: 6,
    paddingTop: 2,
  },
  contextPercent: {
    fontFamily: fonts.cabin,
    fontSize: 12,
    lineHeight: 19.2,
    color: '#697586',
  },
  contextProgressTrack: {
    width: contextProgressWidth,
    height: contextProgressHeight,
    borderRadius: 50,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  contextProgressFill: {
    height: '100%',
    borderRadius: 50,
    backgroundColor: '#4062B9',
  },
  voiceCard: {
    minHeight: voiceCardMinHeight,
    borderRadius: voiceCardRadius,
    backgroundColor: expenseFlowColors.voiceCardBg,
    paddingVertical: expenseFlowLayout.voiceCardPaddingV,
    paddingHorizontal: expenseFlowLayout.voiceCardPaddingH,
    alignItems: 'center',
    gap: contentGap,
  },
  voiceCardIconWrap: {
    width: voiceMicCircleSize,
    height: voiceMicCircleSize,
    borderRadius: voiceMicCircleSize / 2,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceCardTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 20,
    lineHeight: 32,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  voiceCardDescription: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
  },
  voiceRecordingHint: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 281,
    fontFamily: fonts.cabin,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '400',
    color: expenseFlowColors.voiceRecordingHint,
    textAlign: 'center',
  },
  voiceStartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    width: '100%',
    gap: voiceStartButtonGap,
    height: voiceStartButtonHeight,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 50,
    backgroundColor: '#FFFFFF',
  },
  voiceStartLabel: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#4062B9',
  },
  manualDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  manualDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: dividerLineColor,
  },
  manualDividerText: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    color: '#697586',
  },
  amountInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: inputHeight,
    borderRadius: inputRadius,
    borderWidth: 1,
    borderColor: expenseFlowColors.inputBorder,
    backgroundColor: expenseFlowColors.inputBg,
    paddingHorizontal: manualInputPadding,
    gap: 16,
  },
  amountInputPlaceholder: {
    flex: 1,
    fontFamily: fonts.cabin,
    fontSize: 16,
    lineHeight: 25.6,
    color: '#697586',
  },
  loggedSection: {
    gap: expenseFlowLayout.loggedSectionTitleGap,
  },
  loggedEmpty: {
    alignItems: 'center',
    gap: 12,
  },
  loggedEmptyImage: {
    width: 100,
    height: 88,
  },
  loggedEmptyText: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    color: '#7A7A7A',
  },
  voiceLoggedBottomSpacer: {
    flexGrow: 1,
    minHeight: expenseFlowLayout.voiceLoggedBottomMinSpace,
  },
  expenseList: {
    gap: 0,
  },
  expenseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E3E8EF',
  },
  expenseRowLast: {
    borderBottomWidth: 0,
  },
  expenseRowText: {
    flex: 1,
    gap: 2,
    paddingRight: 12,
  },
  expenseRowTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 15,
    lineHeight: 24,
    fontWeight: '700',
    color: '#121926',
  },
  expenseRowMeta: {
    fontFamily: fonts.cabin,
    fontSize: 12,
    lineHeight: 19.2,
    color: expenseFlowColors.loggedMeta,
  },
  expenseRowAmount: {
    fontFamily: fonts.cabinBold,
    fontSize: 15,
    lineHeight: 24,
    fontWeight: '700',
    color: expenseFlowColors.expenseAmount,
  },
  recordingTimer: {
    fontFamily: fonts.cabinBold,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  recordingDot: {
    width: expenseFlowLayout.recordingDotSize,
    height: expenseFlowLayout.recordingDotSize,
    borderRadius: expenseFlowLayout.recordingDotSize / 2,
    backgroundColor: expenseFlowColors.recordingDot,
  },
  recordingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  waveformRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    width: '100%',
    height: 48,
  },
  waveformBar: {
    width: 3,
    borderRadius: 1.5,
    backgroundColor: '#FFFFFF',
  },
  stopButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#4062B9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopButtonSquare: {
    width: 14,
    height: 14,
    borderRadius: 2,
    backgroundColor: '#4062B9',
  },
  stopHint: {
    fontFamily: fonts.cabin,
    fontSize: 12,
    lineHeight: 19.2,
    color: 'rgba(255, 255, 255, 0.85)',
  },
  processingCard: {
    minHeight: voiceCardMinHeight,
    borderRadius: voiceCardRadius,
    backgroundColor: expenseFlowColors.processingCardBg,
    paddingVertical: expenseFlowLayout.voiceCardPaddingV,
    paddingHorizontal: expenseFlowLayout.voiceCardPaddingH,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  processingTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 18,
    lineHeight: 28.8,
    fontWeight: '700',
    color: expenseFlowColors.processingTitle,
    textAlign: 'center',
  },
  processingSubtitle: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 281,
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '400',
    color: expenseFlowColors.processingSubtitle,
    textAlign: 'center',
  },
  confirmCard: {
    minHeight: voiceCardMinHeight,
    alignItems: 'center',
    borderRadius: confirmCardRadius,
    backgroundColor: expenseFlowColors.voiceConfirmCardBg,
    paddingVertical: expenseFlowLayout.voiceCardPaddingV,
    paddingHorizontal: expenseFlowLayout.voiceCardPaddingH,
    justifyContent: 'center',
    gap: 16,
  },
  confirmGotIt: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minWidth: expenseFlowLayout.confirmGotItMinWidth,
    height: expenseFlowLayout.confirmGotItHeight,
    paddingHorizontal: 16,
    borderRadius: 50,
    backgroundColor: '#4062B9',
  },
  confirmGotItIcon: {
    width: 16,
    height: 16,
  },
  confirmGotItLabel: {
    fontFamily: fonts.cabinBold,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  confirmPrompt: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '400',
    color: '#121926',
    textAlign: 'center',
  },
  confirmQuote: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#121926',
    textAlign: 'center',
  },
  rerecordButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    gap: 8,
    height: 48,
    borderRadius: 50,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3E8EF',
  },
  rerecordLabel: {
    fontFamily: fonts.cabinBold,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '700',
    color: '#4062B9',
  },
  loggedExpensesCard: {
    borderRadius: expenseFlowLayout.loggedExpensesCardRadius,
    borderWidth: 1,
    borderColor: '#EEF2F6',
    backgroundColor: '#F8FAFC',
    padding: 16,
  },
  loggedExpenseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 16,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F6',
  },
  loggedExpenseRowLast: {
    paddingBottom: 0,
    marginBottom: 0,
    borderBottomWidth: 0,
  },
  confirmFooter: {
    paddingHorizontal: screenPaddingH,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E3E8EF',
    backgroundColor: '#FFFFFF',
  },
  confirmButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 50,
    borderRadius: 50,
    backgroundColor: '#4062B9',
  },
  confirmButtonLabel: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  field: {
    gap: 8,
  },
  label: {
    fontFamily: fonts.cabinBold,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '700',
    color: '#121926',
  },
  input: {
    height: inputHeight,
    borderRadius: inputRadius,
    borderWidth: 1,
    borderColor: expenseFlowColors.inputBorder,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    fontFamily: fonts.cabin,
    fontSize: 16,
    color: '#121926',
  },
  pressed: {
    opacity: 0.88,
  },
});
