import { StyleSheet } from 'react-native';

import { budgetFlowLayout } from '@/constants/budget-flow';
import { fonts } from '@/constants/fonts';

const {
  detailsHeaderRadius,
  detailsContentPaddingH,
  detailsStatCardRadius,
  detailsStatCardBg,
  detailsStatCardPaddingV,
  detailsStatCardPaddingH,
  detailsStatCardGap,
  detailsStatRowGap,
  detailsBodyGap,
  detailsProgressHeight,
} = budgetFlowLayout;

export const budgetDetailsStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  headerShell: {
    overflow: 'hidden',
    borderBottomLeftRadius: detailsHeaderRadius,
    borderBottomRightRadius: detailsHeaderRadius,
  },
  headerGradient: {
    paddingHorizontal: detailsContentPaddingH,
    paddingBottom: 20,
  },
  headerNav: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  navSide: {
    width: 40,
    alignItems: 'flex-start',
  },
  navSideRight: {
    width: 40,
    alignItems: 'flex-end',
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    fontFamily: fonts.cabinBold,
    fontSize: 17,
    lineHeight: 27.2,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  categoryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  categoryMore: {
    fontFamily: fonts.cabin,
    fontSize: 13,
    lineHeight: 20.8,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  amountThresholdRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  amountColumn: {
    flex: 1,
    gap: 4,
  },
  amount: {
    fontFamily: fonts.cabinBold,
    fontSize: 36,
    lineHeight: 45,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  spentText: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  thresholdPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 50,
    backgroundColor: '#FEFEF3',
    borderWidth: 1,
    borderColor: '#F2F2F2',
    maxWidth: 200,
  },
  thresholdBellIcon: {
    width: 16,
    height: 16,
  },
  thresholdText: {
    fontFamily: fonts.cabinBold,
    fontSize: 12,
    lineHeight: 19.2,
    fontWeight: '700',
    color: '#36994E',
    flexShrink: 1,
  },
  progressTrack: {
    height: detailsProgressHeight,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    overflow: 'hidden',
    marginBottom: 6,
  },
  progressFill: {
    height: '100%',
    borderRadius: 50,
    backgroundColor: '#FFFFFF',
  },
  progressLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  progressEdge: {
    fontFamily: fonts.cabin,
    fontSize: 12,
    lineHeight: 19.2,
    color: 'rgba(255, 255, 255, 0.85)',
  },
  addExpenseButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 50,
    borderRadius: 50,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3E8EF',
  },
  addExpenseIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#4062B9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addExpenseLabel: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#4062B9',
  },
  body: {
    flex: 1,
  },
  statRow: {
    flexDirection: 'row',
    gap: detailsStatRowGap,
  },
  statCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: detailsStatCardGap,
    paddingVertical: detailsStatCardPaddingV,
    paddingHorizontal: detailsStatCardPaddingH,
    borderRadius: detailsStatCardRadius,
    backgroundColor: detailsStatCardBg,
  },
  statTextCol: {
    gap: 2,
  },
  statValue: {
    fontFamily: fonts.cabinBold,
    fontSize: 24,
    lineHeight: 38.4,
    fontWeight: '700',
    color: '#121926',
  },
  statLabel: {
    fontFamily: fonts.cabin,
    fontSize: 13,
    lineHeight: 20.8,
    color: '#697586',
  },
  bodyContent: {
    paddingHorizontal: detailsContentPaddingH,
    paddingTop: 20,
    gap: detailsBodyGap,
  },
  recentExpensesCard: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EEF2F6',
    backgroundColor: '#FFFFFF',
    padding: 16,
    gap: 16,
  },
  recentExpensesCardTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#121926',
  },
  emptyExpenses: {
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 24,
    gap: 12,
  },
  emptyIllustration: {
    width: 120,
    height: 100,
  },
  emptyTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#121926',
    textAlign: 'center',
  },
  emptySubtitle: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    color: '#7A7A7A',
    textAlign: 'center',
    maxWidth: 289,
  },
  expenseList: {
    gap: 0,
  },
  expenseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 16,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F6',
  },
  expenseRowLast: {
    paddingBottom: 0,
    marginBottom: 0,
    borderBottomWidth: 0,
  },
  expenseRowText: {
    flex: 1,
    gap: 4,
    paddingRight: 12,
  },
  expenseRowTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 15,
    lineHeight: 24,
    fontWeight: '700',
    color: '#121926',
  },
  expenseRowMeta: {
    fontFamily: fonts.cabin,
    fontSize: 13,
    lineHeight: 20.8,
    color: '#697586',
  },
  expenseRowAmount: {
    fontFamily: fonts.cabinBold,
    fontSize: 15,
    lineHeight: 24,
    fontWeight: '700',
    color: '#EA4335',
  },
  limitStatusCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CDD5DF',
    paddingTop: 16,
    paddingBottom: 16,
    paddingHorizontal: 14,
    gap: 10,
  },
  limitStatusIconWrap: {
    paddingTop: 2,
  },
  limitStatusTextCol: {
    flex: 1,
    gap: 4,
  },
  limitStatusCardWithin: {
    backgroundColor: '#D9F1DF',
  },
  limitStatusCardNearing: {
    backgroundColor: '#FAF0E2',
    borderColor: '#EECC9E',
  },
  limitStatusCardAt: {
    backgroundColor: '#FBD9D7',
    borderColor: '#F8C0BC',
  },
  limitStatusTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
  },
  limitStatusTitleWithin: {
    color: '#205B2E',
  },
  limitStatusTitleNearing: {
    color: '#8F5200',
  },
  limitStatusTitleAt: {
    color: '#C3382C',
  },
  limitStatusBody: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
  },
  limitStatusBodyWithin: {
    color: '#205B2E',
  },
  limitStatusBodyNearing: {
    color: '#8F5200',
  },
  limitStatusBodyAt: {
    color: '#C3382C',
  },
  pressed: {
    opacity: 0.88,
  },
});
