import { StyleSheet } from 'react-native';

import { budgetFlowColors, budgetFlowLayout } from '@/constants/budget-flow';
import { fonts } from '@/constants/fonts';

const {
  thresholdSheetHeightRatio,
  thresholdSheetRadius,
  thresholdSuccessSheetPaddingTop,
  thresholdSheetPaddingH,
  thresholdSheetContentGap,
  thresholdSheetOptionRadius,
  thresholdSheetOptionPaddingV,
  thresholdSheetOptionPaddingH,
  thresholdSheetButtonHeight,
  thresholdSheetButtonRadius,
  thresholdSheetActionsGap,
} = budgetFlowLayout;

export const editThresholdStyles = StyleSheet.create({
  root: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: thresholdSheetRadius,
    borderTopRightRadius: thresholdSheetRadius,
    paddingHorizontal: thresholdSheetPaddingH,
  },
  sheetForm: {
    height:'80%',
    paddingTop: 10,
    overflow: 'hidden',
  },
  successOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 2,
  },
  successScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(18, 25, 38, 0.28)',
    zIndex: 0,
  },
  successPanel: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: thresholdSheetRadius,
    borderTopRightRadius: thresholdSheetRadius,
    overflow: 'hidden',
    borderTopWidth: 1,
    borderColor: '#E3E8EF',
    paddingTop: thresholdSuccessSheetPaddingTop,
    paddingHorizontal: thresholdSheetPaddingH,
    zIndex: 1,
    shadowColor: '#121926',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.14,
    shadowRadius: 24,
    elevation: 12,
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E3E8EF',
    alignSelf: 'center',
    marginBottom: 12,
  },
  formScroll: {
    flex: 1,
  },
  formDimmed: {
    opacity: 0.55,
  },
  formScrollContent: {
    flexGrow: 1,
    gap: thresholdSheetContentGap,
  },
  title: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 28.8,
    fontWeight: 'semibold',
    color: '#121926',
  },
  subtitle: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    color: '#697586',
  },
  optionsList: {
    gap: 10,
  },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: thresholdSheetOptionPaddingV,
    paddingHorizontal: thresholdSheetOptionPaddingH,
    borderRadius: thresholdSheetOptionRadius,
    backgroundColor: '#EEF2F6',
    borderWidth: 1,
    borderColor: '#E3E8EF',
  },
  optionCardSelected: {
    borderColor: '#4062B9',
    borderWidth: 1.5,
  },
  percentBadge: {
    width: 40,
    height: 40,
    borderRadius: 50,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3E8EF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  percentBadgeText: {
    fontFamily: fonts.cabinBold,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '700',
    color: '#725936',
  },
  optionBody: {
    flex: 1,
    gap: 2,
    paddingRight: 2,
  },
  optionTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '700',
    color: '#121926',
  },
  optionDescription: {
    fontFamily: fonts.cabin,
    fontSize: 12,
    lineHeight: 19.2,
    color: '#697586',
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#CDD5DF',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  radioOuterSelected: {
    borderColor: '#4062B9',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#4062B9',
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: budgetFlowColors.infoBoxBg,
    borderWidth: 1,
    borderColor: budgetFlowColors.infoBoxBorder,
  },
  infoText: {
    flex: 1,
    fontFamily: fonts.cabin,
    fontSize: 12,
    lineHeight: 19.2,
    color: '#697586',
  },
  actions: {
    gap: thresholdSheetActionsGap,
    paddingTop: 4,
  },
  saveButton: {
    height: thresholdSheetButtonHeight,
    borderRadius: thresholdSheetButtonRadius,
    backgroundColor: '#4062B9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonLabel: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  cancelButton: {
    height: thresholdSheetButtonHeight,
    borderRadius: thresholdSheetButtonRadius,
    borderWidth: 1,
    borderColor: '#4062B9',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonLabel: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#4062B9',
  },
  pressed: {
    opacity: 0.9,
  },
  successBody: {
    width: '100%',
  },
});
