import { StyleSheet } from 'react-native';

import { Colors } from '@/constants/Colors';
import { fonts } from '@/constants/fonts';

export const suggestedBudgetStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  fullScroll: {
    flex: 1,
  },
  fullScrollContent: {
    paddingBottom: 20,
  },
  container: {
    paddingHorizontal: 24,
  },
  topBack: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginTop: 16,
    marginBottom: 14,
    gap: 0,
  },
  topBackIcon: {
    width: 24,
    height: 24,
    transform: [{ rotate: '180deg' }],
  },
  topBackLabel: {
    fontFamily: fonts.cabin,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '400',
    color: '#121926',
  },
  title: {
    fontFamily: fonts.cabinBold,
    fontSize: 20,
    lineHeight: 32,
    fontWeight: '700',
    color: '#15213E',
    marginBottom: 4,
  },
  subtitle: {
    fontFamily: fonts.cabin,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '400',
    color: '#697586',
    marginBottom: 16,
  },
  cardsBlock: {
    gap: 12,
    marginBottom: 12,
  },
  card: {
    width: 382,
    height: 184,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#CDD5DF',
    borderRadius: 13,
    backgroundColor: Colors.white,
    paddingTop: 16,
    paddingBottom: 16,
    paddingHorizontal: 14,
    gap: 14,
  },
  cardTopSection: {
    width: 354,
    height: 64,
    gap: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E3E8EF',
    alignSelf: 'center',
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  iconBox: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#F2F2F2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconImage: {
    width: 24,
    height: 24,
  },
  cardMain: {
    flex: 1,
    gap: 2,
  },
  cardTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#20315C',
  },
  cardMeta: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '400',
    color: '#697586',
  },
  amountCol: {
    alignItems: 'flex-end',
    gap: 2,
  },
  amount: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#20315C',
  },
  amountLabel: {
    fontFamily: fonts.cabin,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
    color: '#697586',
  },
  thresholdLabel: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '400',
    color: '#15213E',
  },
  thresholdHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  thresholdIcon: {
    width: 24,
    height: 24,
  },
  thresholdRow: {
    flexDirection: 'row',
    gap: 8,
  },
  thresholdPill: {
    minWidth: 67,
    height: 34,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#E3E8EF',
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 8,
    paddingRight: 16,
    paddingBottom: 8,
    paddingLeft: 16,
  },
  thresholdPillSelected: {
    borderColor: '#E3E8EF',
    backgroundColor: '#BF955B',
  },
  thresholdPillText: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '400',
    color: '#697586',
  },
  thresholdPillTextSelected: {
    fontFamily: fonts.cabinBold,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  totalBanner: {
    width: 382,
    height: 89,
    alignSelf: 'center',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EECC9E',
    backgroundColor: '#FAF0E2',
    padding: 16,
    justifyContent: 'space-between',
    marginTop: 4,
  },
  totalBannerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  totalBannerIcon: {
    width: 24,
    height: 24,
  },
  totalTitle: {
    fontFamily: fonts.cabin,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '500',
    color: '#15213E',
  },
  totalTitleAmount: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '700',
    color: '#697586',
  },
  totalSubtitle: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    fontWeight: '400',
    color: '#697586',
  },
  footer: {
    paddingTop: 8,
    paddingBottom: 12,
    gap: 12,
  },
  secondaryButton: {
    width: '100%',
    maxWidth: 382,
    height: 50,
    alignSelf: 'center',
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#4062B9',
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  secondaryButtonPressed: {
    opacity: 0.9,
  },
  secondaryButtonLabel: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    fontWeight: '700',
    color: '#4062B9',
  },
});
