import { StyleSheet } from 'react-native';

import { fonts } from '@/constants/fonts';

export const budgetsTabStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scroll: {
    flex: 1,
  },
  headerCard: {
    position: 'relative',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    paddingHorizontal: 24,
    paddingBottom: 18,
    gap: 8,
    overflow: 'hidden',
    zIndex: 2,
  },
  headerGradientLayers: {
    ...StyleSheet.absoluteFillObject,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  headerTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 20,
    color: '#121926',
  },
  menuAnchor: {
    position: 'relative',
    alignItems: 'flex-end',
    zIndex: 30,
  },
  infoButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E3E8EF',
  },
  downloadPopoverScreen: {
    position: 'absolute',
    alignItems: 'flex-end',
    zIndex: 40,
  },
  menuCaret: {
    width: 0,
    height: 0,
    marginRight: 8,
    borderLeftWidth: 7,
    borderRightWidth: 7,
    borderBottomWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#FFFFFF',
  },
  downloadButton: {
    minWidth: 146,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3E8EF',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  menuBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
  },
  downloadText: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    color: '#121926',
  },
  overallLabel: {
    fontFamily: fonts.cabin,
    fontSize: 16,
    lineHeight: 25.6,
    color: '#121926',
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  ringBase: {
    width: 94,
    height: 94,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringTextWrap: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringPercent: {
    fontFamily: fonts.cabinBold,
    fontSize: 20,
    color: '#121926',
    lineHeight: 28,
  },
  ringUsed: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    color: '#121926',
  },
  summaryTextCol: {
    flex: 1,
    gap: 2,
  },
  remainingValue: {
    fontFamily: fonts.cabinBold,
    fontSize: 24,
    lineHeight: 38.4,
    color: '#121926',
  },
  remainingLabel: {
    fontFamily: fonts.cabin,
    fontSize: 16,
    lineHeight: 25.6,
    color: '#121926',
  },
  track: {
    height: 13,
    borderRadius: 50,
    backgroundColor: 'rgba(242, 242, 242, 0.5)',
    overflow: 'hidden',
    marginTop: 4,
  },
  trackFill: {
    height: '100%',
    borderRadius: 50,
    backgroundColor: '#FFFFFF',
  },
  scaleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  scaleText: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '500',
    color: '#121926',
  },
  statRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  statCard: {
    flex: 1,
    minHeight: 71,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#F2F2F2',
    backgroundColor: '#E9C085',
    paddingVertical: 8,
    paddingHorizontal: 12,
    justifyContent: 'center',
    gap: 2,
  },
  statValue: {
    fontFamily: fonts.cabinBold,
    fontSize: 24,
    color: '#121926',
    lineHeight: 28,
  },
  statLabel: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    color: '#121926',
    lineHeight: 20,
  },
  body: {
    paddingHorizontal: 24,
    paddingTop: 22,
  },
  allBudgetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 5,
  },
  allBudgetsTitle: {
    fontFamily: fonts.cabinBold,
    fontSize: 16,
    lineHeight: 25.6,
    color: '#121926',
  },
  filterPill: {
    minWidth: 84,
    height: 36,
    borderRadius: 50,
    backgroundColor: '#4062B9',
    borderWidth: 1.5,
    borderColor: '#4062B9',
    paddingVertical: 6,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  filterIcon: {
    width: 18,
    height: 18,
  },
  filterText: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    color: '#FFFFFF',
  },
  filterMenuScreen: {
    position: 'absolute',
    alignItems: 'flex-end',
    zIndex: 40,
  },
  filterMenu: {
    width: 157,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    gap: 10,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 6,
  },
  filterItem: {
    justifyContent: 'center',
  },
  filterItemPressed: {
    opacity: 0.7,
  },
  filterItemText: {
    fontFamily: fonts.cabin,
    fontSize: 14,
    lineHeight: 22.4,
    color: '#697586',
  },
  filterItemTextSelected: {
    fontFamily: fonts.cabinBold,
    color: '#121926',
  },
  list: {
    gap: 14,
    marginTop: 18,
  },
  fabWrap: {
    position: 'absolute',
    right: 24,
  },
  fab: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 10,
  },
  pressed: {
    opacity: 0.88,
  },
});
